dev_addr: 127.0.0.1:8000
site_name: Tactic på Tur
site_description: På tur med Tactic
site_author: Kristian Evers
copyright: Copyright &copy; 2025 Kristian Evers

docs_dir: docs

nav:
- Tactic: index.md
- Sommertogt 2026: sommertogt26.md

# Configuration
theme:
  name: material
  language: da
  #custom_dir: material/overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.sections
    #- navigation.tabs
    - navigation.top
    - navigation.tracking
    #- navigation.path
    # - toc.follow

  font:
    text: Lexend
    code: Roboto Mono
  favicon: images/if-logo-green.png #assets/favicon.png
  icon:
    logo: logo
  logo: images/if-logo-green.png

plugins: []

markdown_extensions:
  - pymdownx.blocks.caption

extra_javascript:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js # leaflet
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css # leaflet
